### ISSUE TITLE
How can I import bmesh?

### ISSUE THREAD

**Issue by caniko2** [TylerGubala/blenderpy#20]
How can I import bmesh outside of blender? Using your package, I can import bpy, but I also need bmesh.

Any suggestions? Thank you

**Comment by TylerGubala** [comment]
I'm not sure what issue you are having exactly; I am able to import it fine:

>Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916
32 bit (Intel)] on win32
>Type "help", "copyright", or "license" for more information.
`>>> import bpy`
>AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
`>>> import bmesh`
`dir(bmesh)`
>['__doc__', '__loader__', '__name__', '__package__', '__spec__',
'from_edit_mesh', 'geometry', 'new', 'ops', 'types', 'update_edit_mesh',
'utils']

Could you please post the error message that you are recieving? If you
continue to have difficulty, you may simply want to switch over to blender
headless mode.

Thanks for your patience.

**Comment by caniko2** [comment]
As you can see, I have already installed the bpy package, but I get module not found error when I try to import bmesh:
![image](https://user-images.githubusercontent.com/29519599/61396737-ab289580-a8c8-11e9-930f-05efc5cf97d7.png)

**Comment by TylerGubala** [comment]
Due to how Blender is structured, you must import bpy prior to importing
bmesh.

**Comment by caniko2** [comment]
That is important information that I couldn't find anywhere. Thank you :)

**Comment by TylerGubala** [comment]
No problem. Sorry for any confusion. If you have any further questions just ask, it is fine to make a github issue for a question that can be answered quickly rather than fighting against it.

In fact, this is true of any Python module that is integrated into the Blender runtime. Why is this you might ask? Because the `c` code which is built into the `bpy.pyd` (native Python module) contains the declaration of `bmesh`, `mathutils`, `gpu`, `bpy_extras`, etc.

You can find a list at the Blender [Documentation Contents page](https://docs.blender.org/api/blender_python_api_current/contents.html#application_modules) under "standalone modules"

**Comment by caniko2** [comment]
Yes, I have been fighting this issue for days.

I looked at the documentation you are linking to, and I did notice that bmesh was standalone. But, I didn't have the insight on bpy.pyd that you have. And didn't know that bpy had to be imported first. Again thank you :)

**Comment by TylerGubala** [comment]
Honestly I have never touched the bmesh module in my code, so I was not
aware of it. Thanks for filing the issue, as now I can add it to the
documentation.

**Comment by yz4322gly** [comment]
感谢您,确实先导入bpy就可以了,虽然导入之后pycharm也不会对他进行任何的提示,但是至少可以正常工作了
