### ISSUE TITLE
can't install bpy on debian using pip3

### ISSUE THREAD

**Issue by pmgou** [TylerGubala/blenderpy#29]
**Describe the bug**
when i run $ pip3 install bpy 
i get the error, on the logfile bellow.. i was trying to find out why in IRC, and they recommended me to fill an issue

**To Reproduce**
1. run `$ pip3 install bpy` on debian unstable

**Expected behavior**
I expected to be able to install this module!

**Desktop (please complete the following information):**
 - OS: debian unstable

```
$ pip3 install bpy
Collecting bpy
  Using cached https://files.pythonhosted.org/packages/18/40/f8166da0a9c7f33bd0a942e9b86e83bd9ab07d85aabff6ffb7e0b939c3cf/bpy-1.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wheel-sa_bsp0j/cmake/
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp8s7abi2y', '--quiet', 'cmake']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bubnskj7/bpy/setup.py", line 397, in <module>
        'install_scripts': InstallBlenderScripts
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp8s7abi2y', '--quiet', 'cmake']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-bubnskj7/bpy/
```
```
$ cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.
```

**Comment by TylerGubala** [comment]
For the moment, you may just want to use the install script [from the wiki](https://github.com/TylerGubala/blenderpy/wiki/Platform:-Linux-Ubuntu), should work somewhat for Debian (I only have Ubuntu desktop).

**Comment by TylerGubala** [comment]
With no additional information I am going to close this as "same as #1 " in a week's time.

**Comment by priyesh16** [comment]
I tried running the script from "https://github.com/TylerGubala/blenderpy/wiki/Platform:-Linux-Ubuntu" and it throws errors like:
 -- Could NOT find OpenEXR (missing: _openexr_LIBRARIES OPENEXR_INCLUDE_DIR) 
-- Could NOT find OpenJPEG (missing: OPENJPEG_LIBRARY OPENJPEG_INCLUDE_DIR) 
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR) 
-- Could NOT find JeMalloc (missing: JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR) 
-- Could NOT find Spacenav (missing: SPACENAV_LIBRARY SPACENAV_INCLUDE_DIR) 
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  build_files/cmake/platform/platform_unix.cmake:301 (find_package)
  CMakeLists.txt:899 (include)

I was wondering if you could write a Docker script for Ubuntu instead so that we know what all packages need to be installed and what environment we are missing.

**Comment by TylerGubala** [comment]
I am not sure what a Docker script is. The script I wrote is just automated
calling of the scripts that Blender Foundation ships out with the source
code. The dependancies could change at any time, and I am not a core
maintainer.

If you wanted to write a Docker script or something, and ran into issues or
had questions, feel free to contact me. Otherwise I have no plans to create
a Docker script at this time.

**Comment by priyesh16** [comment]
Thanks for the prompt response. Actually, from the wiki I was not clear on what the prerequisites are for building blender bpy 2.82 on linux. I have attached a working Dockerfile for building bpy for blender 2.7. Changing the blender version to 2.82 and python version to 3.7.4 throws a lot of compilation errors. Please could you look at it and let me know if you think I am missing any 
linux dependencies.
[Dockerfile.TXT](https://github.com/TylerGubala/blenderpy/files/4534548/Dockerfile.TXT)

**Comment by TylerGubala** [comment]
@priyesh16 It looks like you're missing the additional libraries. Depending on your OS you may require building libraries or installing them from SVN.

I updated the Wiki with some information regarding these libraries. Please see [the new section on precompiled vs self-built binaries](https://github.com/TylerGubala/blenderpy/wiki/Platform:-Linux-Ubuntu#required-libraries)

I tried to capture this change in an update to the script as well, but ultimately I am not too familiar with docker so you may want to refer to the [Building Blender page on Blender Foundation's wiki](https://wiki.blender.org/wiki/Building_Blender/Linux) and follow the steps most appropriate for your use case.

Hope this helps at all.

**Comment by TylerGubala** [comment]
Are you able to build `bpy` without Cycles? Or after [building OpenEXR](https://github.com/AcademySoftwareFoundation/openexr/blob/master/INSTALL.md#building-and-installation) yourself?

**Comment by TylerGubala** [comment]
I am able to build using Raspbian, and 32-bit is not even a supported platform anymore. I had to install `libopenimageio-dev` using `apt` and set "-DWITH_MEM_JEMALLOC=OFF" but in the end it did not give me any trouble, even built it with Cycles.

 I think with the revised script you should be able to build even easier on full-fat 64 bit Debian. Maybe further details with a pull request if you run into an issue and want to share your findings. Once `bpy` is able to have 150Mb upload limit I will post Raspbian wheels, but the build process was pretty straight forward for me, even if I had to roll back to `2.80` just for 32-bit support.

**Comment by TylerGubala** [comment]
Same as #1
