### ISSUE TITLE
Blenderpy build fails with cuda 11.0

### ISSUE THREAD

**Issue by juancamilog** [TylerGubala/blenderpy#45]
Cuda 11 dropped support for architectures older than Maxwell (compute capability < 5.2). building bpy with cuda will fail in this case. A way to fix this if to set `CYCLES_CUDA_BINARIES_ARCH` to exclude `sm_XX` values with `XX` lower than 52, when CUDA_VERSION is higher or equal to 11.0, in the Cmake options to build blender

**Comment by TylerGubala** [comment]
I don't think  I am understanding this.

Is this issue to do with building Blender on machines that it would not otherwise support?

I think I could set the make configure commands to whatever they needed to be [here](https://github.com/TylerGubala/bpy-build/blob/master/bpybuild/make.py#L115) but I would need to know how to properly check compatibility between hardware and CUDA versions.

**Comment by juancamilog** [comment]
This is an issue on trying to build on a machine with CUDA 11. Blender does not officially support CUDA versions higher than 10.1. A possible workaround is, as you suggested, to add the sm architecture option to bpy-build. The blender developers will likely make the appropriate changes to the CMake default options  in future releases, so that the build depends on the CUDA version/detected hardware: https://developer.blender.org/D8063.

I just ended up downgrading to 10.1 and pip install works fine. So, this issue can be closed.

**Comment by TylerGubala** [comment]
Closing per user request
