### ISSUE TITLE
No prebuilt wheels available via pip install bpy && bpy_post_install

### ISSUE THREAD

**Issue by HCAWN** [TylerGubala/blenderpy#50]
**Describe the bug**
Hi Tyler, trying to run `pip install bpy && bpy_post_install` on a new machine:
Win 10 64-bit
python 3.6.6
then the terminal decides to got through with  `Building wheels` etc and this seems to go on for a while and crash (I am not too concerned about that as I'm sure I've not fulfilled the requirements for building the module, I'm more looking to just install a pre-built). so my question is, am I doing something wrong to install the pre-built? I don't recall any tricks before making a `requirements.txt` file being super easy for my project that had `bpy` in it.

I run `pip freeze` on another machine and have `bpy==1.2.3` installed which works great I just want that on the new machine.

If I run `pip install bpy==1.2.3` I get `Could not find a version that satisfies the requirement bpy=1.2.3 (from versions: 0.0.0a0)` which to me suggests there are no builds available?

I then tried `pip install yolk3k` followed by `yolk -V bpy` and that returned bpy 2.82.1 (this module returns what package versions there are for a pip module).  `pip install bpy==2.82.1` returns the same "could not find a version..." message as above.

**Comment by TylerGubala** [comment]
I changed my versioning scheme to match the version of the Blender `bpy` API, so 1.2.3 isn't valid.

I also will not be supporting `bpy` < 2.9 because there have been recent changes to the prebuilt libraries that allow me to build `bpy` much more reliably.

Since I am only building `bpy` 2.9 or higher, you will have to upgrade your Python to 3.7, which matches the version used in `bpy` 2.9.

You can install the wheel files from [the Releases page](https://github.com/TylerGubala/blenderpy/releases).

Apologies for any inconvenience.
