### ISSUE TITLE
bpy reports ImportError: libtbb.so

### ISSUE THREAD

**Issue by Joetib** [TylerGubala/blenderpy#52]
**Describe the bug**
importing bpy raises the error, `ImportError:libttb.so.2:cannot open shared object file: No such file or directory`

**To Reproduce**
1.  Downloaded prebuilt wheels from google drive as linked on this repo's guide for linux. particularly `bpy-2.82-cp37-cp37m-linux_x86_64.whl`.
2. Ran install on Ubuntu. I tried wsl Ubuntu distribution and pythonanywhere using pip on python3.7
2. In a python shell, `import bpy`

**Expected behavior**
No error should have been raised.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.0.4 wsl

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TylerGubala** [comment]
Hi @Joetib !

Apologies, but this will probably not be resolved until I can make a `manylinux` type `wheel` file for the Python module. That has been difficult (at least for me) and the possibly best way to install blender as a Python module on Linux variants (at least for now) would be to follow [Blender Foundation's instructions](https://wiki.blender.org/wiki/Building_Blender/Other/BlenderAsPyModule).

Best of luck and let me know if you need any assistance.

**Comment by Joetib** [comment]
Oh boy... I'll look to it and see how far it goes. Wish me luck.

**Comment by TylerGubala** [comment]
@Joetib Please let me know if you need any help; I am experienced in setting up this Blender build environment.

If it helps you any you could also try [my script](https://github.com/TylerGubala/blenderpy/wiki/Linux-Ubuntu-Manual-Build-Script-(Normal-bpy)#the-build-script) to perform the manual build steps automatically.

**Comment by Joetib** [comment]
Will this be able to give me a wheel? That I can ship to pythonanywhere? Unfortunately, I can't do the build on pythonanywhere directly as I don't have sudo privileges and will need to do that on my local machine. So I need wheels to upload to the server

**Comment by TylerGubala** [comment]
You won't be able to upload a locally built wheel file unless it was built
on the manylinux Docker image (Centos) and had the repair_wheel function
run on it.

Without a wheel that was built in manylinux that has repair_wheel ran on
it, you will get the error message about missing libraries when you install
that version to a machine without the requisite libraries.

For right now, linux remains build local, run local. Unless of course you
want to submit a Pull Request!

**Comment by Joetib** [comment]
Well I'll be glad to be able to help with this so no other person or my future self has to suffer ಡ ͜ ʖ ಡ. But I have no idea how to make that work.
If you could give me some guidance that'd be greatful. By the way I have resorted to buying a windows vps server for the task.
But I still love to be able to fix this. 
Your guidance will be very helpful. I love to get to contribute to open source.

**Comment by Joetib** [comment]
Although I must mention, I am not a super advanced guy. Just a student who loves automation. And python
... And looking to contribute what I can to the world

**Comment by TylerGubala** [comment]
In that case just a heads up that the following still produces build errors
that are not for the faint of heart.

Download and install Docker, git, subversion, and Visual Studio Code.

Clone this repo and open it with Visual Studio code

git checkout -b docker-multistage
mkdir Blender
cd Blender

git clone https://git.blender.org/blender.git

svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib

cd ..
mkdir Optix
cd Optix

Download and install the optix installer for linux 7.1, there is no
automated way to do this I am afraid. Place the .sh auto extract file into
the Optix folder.

Make sure the docker service is running and in VSCode run the Docker -
Build Builder Code.

Go have a good afternoon because this build takes an eternity. If you have
suggestions in this area I would love to hear them. If you're not that
technically inclined, then that's fine too! It just might take a long time
to resolve some of these things. You can always disable cuda and optix in
the cmake configuration if you get build errors but then you lose some of
the more advanced gpu based rendering technologies. It depends what is a
"good enough" build for you.

**Comment by Joetib** [comment]
that sounds tough but I will certainly give it a try.

**Comment by TylerGubala** [comment]
@Joetib if you have not made progress in building your own `bpy` Python module, then you can install from the `wheel` on [the Releases page](https://github.com/TylerGubala/blenderpy/releases).

Please let me know if that works for you. Thanks.

**Comment by Joetib** [comment]
Wow, that saves me a lot. You're awesome.

**Comment by Joetib** [comment]
Gotta test it

**Comment by TylerGubala** [comment]
Please note when testing that you will need the Blender system dependencies
even when installing from wheel. These are listed on the Blender wiki and
it should be as simple as installing system dependencies then installing
the wheel.

**Comment by TylerGubala** [comment]
Closing, assuming that it is solved. 

If after installing the `wheel` file you continue to have issues, post the error log to a new issue. Thanks.
