### ISSUE TITLE
Implement a Donate button

### ISSUE THREAD

**Issue by neoglez** [TylerGubala/blenderpy#58]
I have to say that I have being trying/wasting time to compile/install bpy as a module already over a week or so under Kubuntu 16.04. It did not work as indicated by the official documentation. Also, this repo did not work.
But the wheel https://github.com/TylerGubala/blenderpy/releases/tag/v2.91a0 did :1st_place_medal: :+1:  !!!
If you are doing this in your free time, and letting the people to show their gratitude as a micro donation is OK for you, consider implementing a "Donate" button.
Thanks!

**Comment by TylerGubala** [comment]
Hi @neoglez ,

I'm glad that the `manylinux` `wheel` distributions that I spent so much time on worked for you.

I've put many hours into this project, and a few hundred dollars of equipment even. I imagine that there are many people out there like me, coding for the hope of making the world a better place, or (at least) giving people powerful tools to create and automate.

This is fixed in https://github.com/TylerGubala/blenderpy/commit/8fe1f9b295685dee2aab6852b01284dbf9b9472f

Thanks for the nice words.

Before considering donating I want everyone to know that there are a few things that are better than just throwing money at the project (even though, like most people, I appreciate the donations):

1. If you have an issue, especially ones on unique OS that not everyone uses, either [create a new issue in this repo](https://github.com/TylerGubala/blenderpy/issues/new/choose) or [follow up on Blender Dev Talk](https://devtalk.blender.org/)
2. If you have a feature that you want, fork the code and submit a PR
3. If you really want to financially support something, support the developers of Blender 3d by [joining the Blender Development Fund](https://fund.blender.org/)

This is now closed.
